fix some more bash script madness

diff --git a/scripts/bash/clnJnk b/scripts/bash/clnJnk
--- a/scripts/bash/clnJnk
+++ b/scripts/bash/clnJnk
@@ -3,49 +3,22 @@
 # "bash strict mode"
 set -uo pipefail
 
-# modified version of https://askubuntu.com/a/1386907
-chooseMenu() {
-    local prompt="$1" outvar="$2"
-    shift
-    shift
-    local options=("$@") cur=0 count=${#options[@]} index=0
-    local esc=$(echo -en "\e")
-    printf "[\e[1m\e[93m?\e[0m]%s\n" " $prompt"
-    while true
-    do
-        index=0
-        for o in "${options[@]}"
-        do
-            if [ "$index" == "$cur" ]; then
-                echo -e "> \e[1m\e[92m$o\e[0m\e[3m\e[0m"
-            else
-                echo -e "  \e[90m$o\e[3m\e[0m"
-            fi
-            index=$(( $index + 1 ))
-        done
-        read -s -n3 key
-        if [[ $key == "$esc[A" ]]
-        then cur=$(( $cur - 1 ))
-            [ "$cur" -lt 0 ] && cur=0
-        elif [[ $key == "$esc[B" ]]
-        then cur=$(( $cur + 1 ))
-            [ "$cur" -ge $count ] && cur=$(( $count - 1 ))
-        elif [[ $key == "" ]]
-        then break
-        fi
-        echo -en "\e[${count}A"
-    done
-    printf -v $outvar "${options[$cur]}"
+# tweaked fzf chooser
+fzf_choose() {
+    local choices=("$@")
+    local prompt="${choices[-2]}"
+    local output="${choices[-1]}"
+    unset 'choices[-1]' && unset 'choices[-1]'
+    printf -v $output \
+    "$(printf "%s\n" "${choices[@]}" \
+    | fzf --multi --prompt="$prompt > ")"
 }
 
-# check how full the caches are
-getCacheSpace() {
+# check cache spaces
+get_cache_space() {
     PACMAN_CACHE=$(/bin/du -h /var/cache/pacman/pkg/ | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
-    printf "\e[1m\e[93m → \e[0m%s\n" " pacman: ${PACMAN_CACHE}"
     PARU_CACHE=$(/bin/du -h "/home/$_USER/.cache/paru/clone/" | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
-    printf "\e[1m\e[93m → \e[0m%s\n" " paru: ${PARU_CACHE}"
     PIP_CACHE=$(/bin/du -h "/home/$_USER/.cache/pip/" | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
-    printf "\e[1m\e[93m → \e[0m%s\n" " pip: ${PIP_CACHE}"
 }
 
 # detect su system
@@ -67,12 +40,24 @@ else
     _USER=$USER
 fi
 
+# check if fzf is available
+if ! command -v fzf >> /dev/null; then
+    printf "[\e[1m\e[91m✗\e[0m]%s\n" " needs 'fzf' installed!"
+fi
+
 # get space occupation
 printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Checking Caches.."
-getCacheSpace
+PACMAN_CACHE=$(/bin/du -h /var/cache/pacman/pkg/ | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
+PARU_CACHE=$(/bin/du -h "/home/$_USER/.cache/paru/clone/" | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
+PIP_CACHE=$(/bin/du -h "/home/$_USER/.cache/pip/" | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
+
+# print all caches
+printf "\e[1m\e[93m → \e[0m%s\n" " pacman: ${PACMAN_CACHE}"
+printf "\e[1m\e[93m → \e[0m%s\n" " paru: ${PARU_CACHE}"
+printf "\e[1m\e[93m → \e[0m%s\n" " pip: ${PIP_CACHE}"
 
 # start selection here
-selections=(
+OPTIONS=(
     "pacman"
     "paru"
     "pip"
@@ -80,43 +65,53 @@ selections=(
     "flatpak"
     "none"
 )
-chooseMenu "What to clean?" selected_choice ${selections[@]}
+fzf_choose "${OPTIONS[@]}" "What to clean?" CHOICES
 
-_ERROR=0
+for _CHOICE in ${CHOICES}; do
+    _ERROR=0
+    case $_CHOICE in
+        "pacman")
+            $SU_SYS pacman -Scc --noconfirm >> /dev/null \
+            && $SU_SYS rm -rf /var/cache/pacman/pkg/*;
+            _ERROR=$?
+            _OLD_PACMAN_CACHE=$PACMAN_CACHE
+            PACMAN_CACHE=$(/bin/du -h /var/cache/pacman/pkg/ | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
+            printf "[\e[1m\e[93m⧗\e[0m]%s\n" " pacman: ${_OLD_PACMAN_CACHE} → ${PACMAN_CACHE}"
+        ;;
+        "paru")
+            rm -rf /home/$_USER/.cache/paru/clone/*;
+            _ERROR=$?
+            _OLD_PARU_CACHE=$PARU_CACHE
+            PARU_CACHE=$(/bin/du -h "/home/$_USER/.cache/paru/clone/" | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
+            printf "[\e[1m\e[93m⧗\e[0m]%s\n" " paru: ${_OLD_PARU_CACHE} → ${PARU_CACHE}"
+        ;;
+        "pip")
+            rm -rf /home/$_USER/.cache/pip/*;
+            _ERROR=$?
+            _OLD_PIP_CACHE=$PIP_CACHE
+            PIP_CACHE=$(/bin/du -h "/home/$_USER/.cache/pip/" | cut -d '/' -f 1 | tail -n 1 | tr -d '\t' 2> /dev/null)
+            printf "[\e[1m\e[93m⧗\e[0m]%s\n" " pip: ${_OLD_PIP_CACHE} → ${PIP_CACHE}"
+        ;;
+        "orphans")
+            if [ $(pacman -Qtdq | wc -l) -gt 0 ]; then
+                $SU_SYS pacman -Rs --noconfirm $(pacman -Qtdq) >> /dev/null;
+                _ERROR=$?
+            fi
+        ;;
+        "flatpak")
+            flatpak remove --unused --noninteractive >> /dev/null;
+            _ERROR=$?
+        ;;
+        "none")
+            printf "[\e[1m\e[92m✓\e[0m]%s\n" " Goodbye"
+            exit 0
+        ;;
+    esac
+    if ! [ $_ERROR -eq 0 ]; then
+        printf "[\e[1m\e[91m✗\e[0m]%s\n" " Error while cleaning"
+        exit 1
+    fi
+done
 
-case $selected_choice in
-    "pacman")
-        $SU_SYS pacman -Scc --noconfirm >> /dev/null \
-        && $SU_SYS rm -rf /var/cache/pacman/pkg/*;
-        _ERROR=$?
-    ;;
-    "paru")
-        rm -rf /home/$_USER/.cache/paru/clone/*;
-        _ERROR=$?
-    ;;
-    "pip")
-        rm -rf /home/$_USER/.cache/pip/*;
-        _ERROR=$?
-    ;;
-    "orphans")
-        $SU_SYS pacman -Rs --noconfirm $(pacman -Qtdq) >> /dev/null;
-        _ERROR=$?
-    ;;
-    "flatpak")
-        flatpak remove --unused --noninteractive >> /dev/null;
-        _ERROR=$?
-    ;;
-    "none")
-        printf "[\e[1m\e[92m✓\e[0m]%s\n" " Goodbye"
-        exit 0
-    ;;
-esac
-
-if [ $_ERROR -eq 0 ]; then
-    printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
-    getCacheSpace
-    exit 0
-else
-    printf "[\e[1m\e[91m✗\e[0m]%s\n" " Error while cleaning"
-    exit 1
-fi
+printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
+exit 0
diff --git a/scripts/bash/mntExt b/scripts/bash/mntExt
--- a/scripts/bash/mntExt
+++ b/scripts/bash/mntExt
@@ -3,117 +3,68 @@
 # "bash strict mode"
 set -uo pipefail
 
-# modified version of https://askubuntu.com/a/1386907
-chooseMenu() {
-    local prompt="$1" outvar="$2"
-    shift
-    shift
-    local options=("$@") cur=0 count=${#options[@]} index=0
-    local esc=$(echo -en "\e")
-    scriptFeedback prompt "$prompt"
-    while true
-    do
-        index=0
-        for o in "${options[@]}"
-        do
-            local spc=""
-            if [ $isDrivePrompt = true ]; then
-                spc=" ($(/bin/lsblk -l | /bin/grep "$o" | tr -s ' ' ' ' \
-                | cut -d ' ' -f 4))"
-            fi
-            if [ "$index" == "$cur" ]; then
-                echo -e "> \e[1m\e[92m$o\e[0m\e[3m$spc\e[0m"
-            else
-                echo -e "  \e[90m$o\e[3m$spc\e[0m"
-            fi
-            index=$(( $index + 1 ))
-        done
-        read -s -n3 key
-        if [[ $key == "$esc[A" ]]
-        then cur=$(( $cur - 1 ))
-            [ "$cur" -lt 0 ] && cur=0
-        elif [[ $key == "$esc[B" ]]
-        then cur=$(( $cur + 1 ))
-            [ "$cur" -ge $count ] && cur=$(( $count - 1 ))
-        elif [[ $key == "" ]]
-        then break
-        fi
-        echo -en "\e[${count}A"
-    done
-    printf -v $outvar "${options[$cur]}"
-}
-
-# give user feedback
-scriptFeedback() {
-    case $1 in
-        prompt)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "3" "?" " $2"
-            ;;
-        error)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "1" "✗" " $2"
-            exit 1
-            ;;
-        success)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "2" "✓" " $2"
-            ;;
-        proc)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "3" ":" " $2"
-            ;;
-    esac
+# tweaked fzf chooser
+fzf_choose() {
+    local choices=("$@")
+    local prompt="${choices[-2]}"
+    local output="${choices[-1]}"
+    unset 'choices[-1]' && unset 'choices[-1]'
+    printf -v $output \
+    "$(printf "%s\n" "${choices[@]}" \
+    | fzf --multi --prompt="$prompt > ")"
 }
 
 # drive chooser
-chooseDrive() {
-    adj_selections=""
-    for d in $FETCHDRIVES; do
-        mountStat=$(lsblk -l | grep "$d" | tr -s ' ' ' ' \
+choose_drive() {
+    FETCHDRIVES=$(lsblk -l | /bin/grep -E \
+    'sd[a-zA-Z][0-9]|nvme[0-9]n[0-9]p[0-9]' \
+    | tr -s ' ' ' ' | cut -d ' ' -f 1)
+    local _OPTIONS=""
+    for d in ${FETCHDRIVES}; do
+        mountStat=$(lsblk -l | /bin/grep "$d" | tr -s ' ' ' ' \
         | cut -d ' ' -f 7)
         if [ -z "$mountStat" ]; then
-            adj_selections="$adj_selections""$d "
+            _OPTIONS="${_OPTIONS}""${d} "
         fi
     done
-    if [ -z "$adj_selections" ]; then
-        scriptFeedback proc "No mountable drives found!"
+    if [ -z "${_OPTIONS}" ]; then
+        printf "[\e[1m\e[92m✓\e[0m]%s\n" " No mountable drives"
         exit 0
     else
-        isDrivePrompt=true
-        chooseMenu "What Drive to mount?" \
-        selected_choice ${adj_selections[@]}
-        DRIVE=$selected_choice
-        isDrivePrompt=false
+        fzf_choose "${_OPTIONS[@]}" \
+        "What Drive to mount?" DRIVE
     fi
 }
 
 # fs chooser
-chooseFS() {
-    selections=(
+choose_fs() {
+    local _OPTIONS=(
         "auto"
         "ntfs3"
         "ext4"
-        "xfs"
         "vfat"
     )
-    chooseMenu "What filesystem to mount with?" \
-    selected_choice ${selections[@]}
-    FS=$selected_choice
+    fzf_choose "${_OPTIONS[@]}" \
+    "What filesystem to mount with?" FS
 }
 
 # unmount mountpoint if user wants
-handleUnmount() {
-    selections=(
+handle_unmount() {
+    local _OPTIONS=(
         "no"
         "yes"
     )
-    chooseMenu "Mountpoint already occupied, unmount?" \
-    selected_choice ${selections[@]}
-    if [ "$selected_choice" == "yes" ]; then
+    fzf_choose "${_OPTIONS[@]}" \
+    "Mountpoint already occupied, unmount?" UMOUNT_CHOICE
+    if [ "${UMOUNT_CHOICE}" == "yes" ]; then
         if 
-        $SU_SYS /bin/umount -l "$MOUNTPOINT"; 
+        $SU_SYS umount -l "${MOUNTPOINT}"; 
         then
-            scriptFeedback success "Successfully unmounted!"
+            printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
             exit 0
         else
-            scriptFeedback error "Some error occured!"
+            printf "[\e[1m\e[91m✗\e[0m]%s\n" " Unmount error"
+            exit 1
         fi
     else
         exit 0
@@ -121,25 +72,24 @@ handleUnmount() {
 }
 
 # mount drive after selections
-handleMount() {
-    DRIVESPACE=$(lsblk -l | grep "$DRIVE" | tr -s ' ' ' ' \
-    | cut -d ' ' -f 4)
-    DRIVE="/dev/""$DRIVE"
-    scriptFeedback proc "Mounting '$DRIVE' ($DRIVESPACE) \
-with '$FS' to '$MOUNTPOINT\'"
-    selections=(
+handle_mount() {
+    DRIVESPACE=$(lsblk -l | /bin/grep "$DRIVE" | tr -s ' ' ' ' | cut -d ' ' -f 4)
+    printf "[\e[1m\e[93m⧗\e[0m]%s\n" \
+    " Mounting '/dev/${DRIVE}' (${DRIVESPACE}) with '${FS}' to '${MOUNTPOINT}'"
+    local _OPTIONS=(
         "no"
         "yes"
     )
-    chooseMenu "Correct?" selected_choice ${selections[@]}
-    if [ "$selected_choice" == "yes" ]; then
+    fzf_choose "${_OPTIONS[@]}" "Correct?" MOUNT_CHOICE
+    if [ "${MOUNT_CHOICE}" == "yes" ]; then
         if
-        $SU_SYS /bin/mount -t "$FS" "$DRIVE" "$MOUNTPOINT";
+        $SU_SYS mount -t "${FS}" "/dev/${DRIVE}" "${MOUNTPOINT}";
         then
-            scriptFeedback success "Successfully mounted!"
+            printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
             exit 0
         else
-            scriptFeedback error "Some error occured!"
+            printf "[\e[1m\e[91m✗\e[0m]%s\n" " Mount error"
+            exit 1
         fi
         
     else
@@ -148,38 +98,27 @@ with '$FS' to '$MOUNTPOINT\'"
 }
 
 # detect su system
-if command -v sudo >> /dev/null; then
-    SU_SYS="sudo"
-else
-    SU_SYS="doas"
-fi
-
-# check for root run
-if [ "$EUID" -eq 0 ]; then
-    # dont use sudo or doas
-    scriptFeedback success "Root Detected"
+if [ $EUID -eq 0 ]; then
     SU_SYS=""
+else
+    if command -v sudo >> /dev/null; then
+        SU_SYS="sudo"
+    else
+        SU_SYS="doas"
+    fi
 fi
 
-# no drive prompt
-isDrivePrompt=false
-# first get list of mountable drives
-FETCHDRIVES=$(/bin/lsblk -l | grep -E \
-'sd[a-zA-Z][0-9]|nvme[0-9]n[0-9]p[0-9]' \
-| tr -s ' ' ' ' | cut -d ' ' -f 1)
-
-# get supplied mountpoint
-if [ -v 1 ]; then
-    MOUNTPOINT=$1
-else
-    scriptFeedback error "Supply a mountpoint!"
+# check for mountpoint
+if ! [ -v 1 ]; then
+    printf "[\e[1m\e[91m✗\e[0m]%s\n" " No mountpoint specified"
+    exit 1
 fi
 
 # then check if mountpoint is occupied, if not continue
-if /bin/mountpoint "$MOUNTPOINT" >> /dev/null; then
-    handleUnmount
+if mountpoint "${MOUNTPOINT}" >> /dev/null; then
+    handle_unmount
 else
-    chooseDrive
-    chooseFS
-    handleMount
+    choose_drive
+    choose_fs
+    handle_mount
 fi
diff --git a/scripts/bash/mntSMB b/scripts/bash/mntSMB
--- a/scripts/bash/mntSMB
+++ b/scripts/bash/mntSMB
@@ -3,124 +3,72 @@
 # "bash strict mode"
 set -uo pipefail
 
-# modified version of https://askubuntu.com/a/1386907
-chooseMenu() {
-    local prompt="$1" outvar="$2"
-    shift
-    shift
-    local options=("$@") cur=0 count=${#options[@]} index=0
-    local esc=$(echo -en "\e")
-    scriptFeedback prompt "$prompt"
-    while true
-    do
-        index=0
-        for o in "${options[@]}"
-        do
-            if [ "$index" == "$cur" ]; then
-                echo -e "> \e[1m\e[92m$o\e[0m\e[3m\e[0m"
-            else
-                echo -e "  \e[90m$o\e[3m\e[0m"
-            fi
-            index=$(( $index + 1 ))
-        done
-        read -s -n3 key
-        if [[ $key == "$esc[A" ]]
-        then cur=$(( $cur - 1 ))
-            [ "$cur" -lt 0 ] && cur=0
-        elif [[ $key == "$esc[B" ]]
-        then cur=$(( $cur + 1 ))
-            [ "$cur" -ge $count ] && cur=$(( $count - 1 ))
-        elif [[ $key == "" ]]
-        then break
-        fi
-        echo -en "\e[${count}A"
-    done
-    printf -v $outvar "${options[$cur]}"
-}
+# settings
+SMB_CREDS="/home/${_USER}/.smbcreds"
+SMB_CFG="/home/${_USER}/.smbcfg"
 
-# give user feedback
-scriptFeedback() {
-    case $1 in
-        prompt)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "3" "?" " $2"
-        ;;
-        error)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "1" "✗" " $2"
-            exit 1
-        ;;
-        success)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "2" "✓" " $2"
-        ;;
-        proc)
-            printf "[\e[1m\e[9%sm%s\e[0m]%s\n" "3" ":" " $2"
-        ;;
-    esac
-}
-
-# check if multiple Servers in config exist
-handleMultiple() {
-    shares=()
-    for shr in {1..10}; do
-        if [ -v "SMB_SERVER_$shr" ]; then
-            server=SMB_SERVER_${shr}
-            shares+=(${!server})
-        fi
-    done
-    shareCount=${#shares[@]}
-    if [ $shareCount -gt 1 ]; then
-        chooseMenu "What Drive to mount?" \
-        selected_choice ${shares[@]}
-        SMB_SERVER=$selected_choice
-    else
-        SMB_SERVER=$SMB_SERVER_1
-    fi
-    scriptFeedback proc "Share: $SMB_SERVER"
-}
-
-# handle unmount SMB
-handleUnmount() {
-    selections=(
-        "no"
-        "yes"
-    )
-    chooseMenu "Mountpoint already occupied, unmount?" \
-    selected_choice ${selections[@]}
-    if [ "$selected_choice" == "yes" ]; then
-        if
-        $SU_SYS /bin/umount -l "$SMB_MOUNT";
-        then
-            scriptFeedback success "Successfully unmounted!"
-            exit 0
-        else
-            scriptFeedback error "Some error occured!"
-        fi
-    else
-        exit 0
-    fi
+# tweaked fzf chooser
+fzf_choose() {
+    local choices=("$@")
+    local prompt="${choices[-2]}"
+    local output="${choices[-1]}"
+    unset 'choices[-1]' && unset 'choices[-1]'
+    printf -v $output \
+    "$(printf "%s\n" "${choices[@]}" \
+    | fzf --multi --prompt="$prompt > ")"
 }
 
 # handle mount SMB
-handleMount() {
+handle_mount() {
+    SHARES=()
+    for i in {1..10}; do
+        if [ -v "SMB_SERVER_${i}" ]; then
+            _SERVER="SMB_SERVER_${i}"
+            SHARES+=(${!_SERVER})
+        fi
+    done
+    SHARE_COUNT=${#SHARES[@]}
+    if [ $SHARE_COUNT -gt 1 ]; then
+        fzf_choose "${SHARES[@]}" "What Share to mount?" SMB_SERVER
+    else
+        SMB_SERVER=$SMB_SERVER_1
+    fi
     if
-    $SU_SYS /bin/mount "$SMB_SERVER" -t cifs \
+    $SU_SYS mount "$SMB_SERVER" -t cifs \
     -o user,uid=1000,rw,credentials="$SMB_CREDS" "$SMB_MOUNT";
     then
-        scriptFeedback success "Successfully mounted!"
+        printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
         exit 0
     else
-        scriptFeedback error "Some error occured!"
+        printf "[\e[1m\e[91m✗\e[0m]%s\n" " Mount error"
+        exit 1
     fi
 }
 
-# detect su system
-if command -v sudo >> /dev/null; then
-    SU_SYS="sudo"
-else
-    SU_SYS="doas"
-fi
+# handle unmount SMB
+handle_unmount() {
+    local _OPTIONS=(
+        "no"
+        "yes"
+    )
+    fzf_choose "${_OPTIONS[@]}" "Mountpoint occupied, unmount?" UNMOUNT_CHOICE
+    if [ "${UNMOUNT_CHOICE}" == "yes" ]; then
+        if
+        $SU_SYS umount -l "$SMB_MOUNT";
+        then
+            printf "[\e[1m\e[92m✓\e[0m]%s\n" " Done"
+            exit 0
+        else
+            printf "[\e[1m\e[91m✗\e[0m]%s\n" " Unmount error"
+            exit 1
+        fi
+    else
+        exit 0
+    fi
+}
 
 # check for root run and react accordingly
-if [ "$EUID" -eq 0 ]; then
+if [ $EUID -eq 0 ]; then
     SU_SYS=""
     if [ -v SUDO_USER ]; then
         _USER=$SUDO_USER
@@ -129,24 +77,26 @@ if [ "$EUID" -eq 0 ]; then
     fi
 else
     _USER=$USER
+    if command -v sudo >> /dev/null; then
+        SU_SYS="sudo"
+    else
+        SU_SYS="doas"
+    fi
 fi
 
-# settings
-SMB_CREDS="/home/$_USER/.smbcreds"
-SMB_CFG="/home/$_USER/.smbcfg"
-
 # check if config files exist read, else exit
-if [ -e "$SMB_CREDS" ] && [ -e "$SMB_CFG" ]; then
-    scriptFeedback success "SMB config files found!"
-    . "$SMB_CFG"
+if [ -e "${SMB_CREDS}" ] && [ -e "${SMB_CFG}" ]; then
+    printf "[\e[1m\e[93m⧗\e[0m]%s\n" " Loading SMB config.."
+    . "${SMB_CFG}"
 else
-    scriptFeedback error "No SMB config files found for user '$1'!"
+    printf "[\e[1m\e[91m✗\e[0m]%s\n" \
+    " No SMB config files found for user '${1}'!"
+    exit 1
 fi
 
 # check if mountpoint is occupied, if not, mount
-if /bin/mountpoint "$SMB_MOUNT" >> /dev/null; then
-    handleUnmount
+if mountpoint "${SMB_MOUNT}" >> /dev/null; then
+    handle_unmount
 else
-    handleMultiple
-    handleMount
+    handle_mount
 fi
